export enum RtcCallState {
  NONE = "NONE",
  INITIATED = "INITIATED",
  RECEIVING = "RECEIVING",
  ACCEPTED = "ACCEPTED",
  NOT_ANSWERED = "NOT_ANSWERED",
  DECLINED = "DECLINED",
  CANCELED = "CANCELED",
  CONNECTED = "CONNECTED",
  COMPLETED = "COMPLETED"
}
